# Generated by Django 4.0.2 on 2022-02-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_scraper_main', '0002_customrequirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequirements',
            name='to_email',
            field=models.EmailField(default='pavel@karpidesign.com', max_length=254),
            preserve_default=False,
        ),
    ]
